'''
创建脉冲类，定义传感中的虚拟脉冲，可用于构建脉冲序列及其哈密顿量
支持旋转系和实验系的脉冲定义，支持控制旋转角度
'''

import numpy as np
from qutip import *
from abc import ABC, abstractmethod

from sqc.devices.transmon import TransmonQubit
from sqc.control.flux_signal import Signal


class PulseBase(ABC):
    """Base contract for pulse-like objects.

    Subclasses expose a QuTiP-list Hamiltonian and a time axis.
    """

    @property
    @abstractmethod
    def hamiltonian(self):
        """QuTiP list-format Hamiltonian generated by this pulse."""

    @property
    @abstractmethod
    def t_list(self):
        """Time axis for the pulse Hamiltonian coefficients."""

    @property
    @abstractmethod
    def frame(self):
        """Reference frame identifier used by the pulse."""

    @abstractmethod
    def get_hamiltonian(self):
        """Return the pulse Hamiltonian in QuTiP list format."""

class Pulse:
    def __init__(self, frame = 0, omega_d = 0.0, phase = 0.0, Omega = None, is_rwa = True, qubit=None):
        '''
        初始化Pulse对象
        :param frame: 参考系，0-实验系，1-旋转系
        :param omega_d: 驱动频率（GHz）
        :param phase: 旋转轴相位（rad），旋转轴在xy平面的分量与Phase有关，在z轴分量由失谐调节
        :param Omega: Rabi 频率包络线（GHz），属于Signal类对象或常数
        :param is_rwa: 是否使用旋转波近似
        :param qubit: 作用的Qubit对象，用于获取能级数（可选，如果未提供则默认使用2能级）
        '''
        self.frame = frame
        self.omega_d = omega_d
        self.phase = phase
        self.Omega = Omega
        self.is_rwa = is_rwa
        self.qubit = qubit
        if qubit is not None:
            self.n_levels = qubit.n_levels
        else:
            self.n_levels = 2  # 默认两能级，向后兼容

        self.hamiltonian, self.t_list = self.get_hamiltonian()


    def get_Rabi_frequency(self, t):
        '''
        获取脉冲在时间t处的Rabi频率
        :param t: 时间点（ns）
        '''
        if isinstance(self.Omega, Signal):
            return self.Omega.value_at(t)
        
        elif isinstance(self.Omega, (int, float)):
            return self.Omega
    
    def get_hamiltonian_at(self, t):
        '''
        获取脉冲在时间t处的哈密顿量，使用湮灭算符a和产生算符a^†表示
        :param t: 时间点（ns）
        '''
        n = self.n_levels
        a = destroy(n)  # 湮灭算符
        adag = create(n)  # 产生算符
        Omega_t = self.get_Rabi_frequency(t)
        if self.frame == 0:  # 实验系
            phase_term = self.omega_d * t + self.phase
            H_pulse = Omega_t * np.cos(phase_term) * (a + adag)
            return H_pulse
        else:  # 旋转系
            if self.is_rwa:
                H_rwa = Omega_t / 2 * (a * np.exp(1j * self.phase) + adag * np.exp(-1j * self.phase))
                return H_rwa
            else:
                H_rwa = Omega_t / 2 * (a * np.exp(1j * self.phase) + adag * np.exp(-1j * self.phase))
                phase_cr = 2 * self.omega_d * t + self.phase
                H_cr = Omega_t / 2 * (a * np.exp(-1j * phase_cr) + adag * np.exp(1j * phase_cr))
                return H_rwa + H_cr
    
    def get_hamiltonian(self):
        '''
        获取脉冲在时间t处的哈密顿量，使用湮灭算符a和产生算符a^†表示
        返回qutip列表格式
        :param t: 时间点（ns）
        '''
        n = self.n_levels
        a = destroy(n)  # 湮灭算符
        adag = create(n)  # 产生算符
        t_list = np.asarray(self.Omega.t_list)
        #Omega = np.array([self.get_Rabi_frequency(t) for t in self.Omega.t_list]) if isinstance(self.Omega, Signal) else self.Omega
        # 直接访问Omega.signal，计算复杂度从O(N^2)降到O(N)，大幅提升效率
        Omega = np.array(self.Omega.signal, dtype=float) if isinstance(self.Omega, Signal) else self.Omega
        if self.frame == 0:  # 实验系
            coeff = Omega * np.cos(self.omega_d * t_list + self.phase)
            H = [[a + adag,  coeff]]

        else:  # 旋转系
            # rwa
            H1 = 0.5 * (a * np.exp(1j * self.phase) + adag * np.exp(-1j * self.phase))
            coeff_rwa = Omega
            if self.is_rwa:
                H = [[H1,  coeff_rwa]]
            else:
                # cr
                H_cr1 = 0.5 * a * np.exp(-1j * self.phase)
                H_cr2 = 0.5 * adag * np.exp(1j * self.phase)
                coeff_cr1 = Omega * np.exp(-2j * self.omega_d * t_list)
                coeff_cr2 = Omega * np.exp(2j * self.omega_d * t_list)
                H = [[H1, coeff_rwa], [H_cr1,  coeff_cr1], [H_cr2,  coeff_cr2]]
        return H, t_list
    
    def get_angle(self, qubit:TransmonQubit=None):
        '''
        获取脉冲的旋转角度，与qubit的性质有关
        :param qubit: 作用的Qubit对象（可选），如果未提供则使用初始化时传入的qubit
        '''
        if qubit is not None:
            self.qubit = qubit
            self.n_levels = qubit.n_levels

        n_levels = self.n_levels
        psi_0 = qubit.state if self.qubit is not None else basis(n_levels, 0)
        t_list = self.Omega.t_list
        dt = t_list[1] - t_list[0]
        U = qeye(n_levels)
        for i in range(len(t_list)-1):
            t_i = ( t_list[i] + t_list[i+1] ) / 2
            H_i = self.get_hamiltonian(t_i)
            U_i = (-1j * H_i * dt).expm()
            U = U_i * U
        # 计算旋转角度
        psi_final = U * psi_0  
        rho_sub = psi_final.ptrace([0]) if n_levels > 2 else psi_final * psi_final.dag()
        a = U[0, 0]
        a = np.real(a)
        angle = 2 * np.arccos(a)
        c0 = psi_final[0,0]
        c1 = psi_final[1,0]
        norm = np.sqrt(abs(c0)**2 + abs(c1)**2)
    
    # 4. 计算极角 Theta (Rabi Angle)
    # P1 = |c1|^2 (处于激发态的概率)
    # P1 = sin^2(theta/2)  =>  theta = 2 * arcsin(sqrt(P1))
        p1 = abs(c1)**2 / norm**2
        theta = 2 * np.arcsin(np.sqrt(p1))
    
    # 5. 计算方位角 Phi (Phase)
    # 相对相位：c1 / c0 = tan(theta/2) * exp(i*phi)
    # phi = arg(c1) - arg(c0)
        phi = np.angle(c1) - np.angle(c0)
    
        return theta, phi  # 返回两个角度更完整
    
    def get_angle_simple(self):
        '''
        获取脉冲的旋转角度（rad），考虑共振情况，角度等于Rabi频率积分
        '''
        num_points = 1000
        t_list = np.linspace(self.Omega.t_list[0], self.Omega.t_list[-1], num_points)  # 假设脉冲持续时间为1ns
        Omegas = [self.get_Rabi_frequency(t) for t in t_list]
        angle = np.trapezoid(Omegas, t_list)  # 计算积分
        return angle
    
    def back_pulse(self):
        '''
        背景脉冲（可加噪声）
        '''
        return np.zeros_like(self.Omega.t_list)

    def get_kernel(self, qubit):
        '''
        获取脉冲的控制核函数，表示该脉冲对测量结果的影响，未来可以直接用来做卷积和反卷积
        :param qubit: 作用的Qubit对象，用于计算控制核
        '''
        from sqc.reconstruction.kernel import KernelEstimator

        estimator = KernelEstimator(stim_amplitude=1.0, stim_width=2.0)
        self.t_samples, self.kernel = estimator.estimate_legacy_single_pulse(
            self, qubit
        )
        return self.t_samples, self.kernel



class CompositePulse:
    def __init__(self, pulses):
        '''
        初始化CompositePulse对象，包含多个Pulse对象
        :param pulses: Pulse对象列表
        '''
        self.pulses = pulses
        self.t_list = self.get_t_list()
        self.frame = pulses[0].frame 
        self.omega_d = pulses[0].omega_d
        self.hamiltonian, _ = self.get_hamiltonian()

    def get_t_list(self):
        '''
        获取复合脉冲的时间列表，返回数组形式
        '''
        t_list = []
        curr = 0.0
        for pulse in self.pulses:
            pulse_list = [t + curr for t in pulse.Omega.t_list]  # 避免重复时间点
            t_list.extend(pulse_list)
            if pulse_list:
                # 保证t_list没有重复的时间点
                curr = pulse_list[-1] + 1e-9  # 在最后一个时间点基础上加一个小的时间间隔，避免重复，同时两个脉冲之间有一个小的间隔，从而避开coeff边界的处理
        return np.array(t_list)
    
    def get_Omega(self,t):
        '''
        获取复合脉冲的Rabi频率包络线，返回t时刻的幅值
        '''
        curr = 0.0
        for pulse in self.pulses:
            if t >= curr and t <= curr + pulse.Omega.t_list[-1]:
                return pulse.get_Rabi_frequency(t - curr)
            curr += pulse.Omega.t_list[-1]


    def get_hamiltonian_at(self, t):
        '''
        获取复合脉冲在时间t处的哈密顿量
        '''
        curr = 0.0
        for pulse in self.pulses:
            if t >= curr and t <= curr + pulse.Omega.t_list[-1]:
                return pulse.get_hamiltonian_at(t - curr)
            curr += pulse.Omega.t_list[-1]

        return Qobj(np.zeros((pulse.n_levels, pulse.n_levels)))  # 超出范围返回零哈密顿量
    
    def get_hamiltonian(self):
        '''
        获取复合脉冲的哈密顿量，返回qutip列表格式
        '''
        t_global = np.asarray(self.t_list)
        N = len(t_global)
        hamiltonian = []
        curr = 0.0
        for pulse in self.pulses:
            term_curr, t_local = pulse.hamiltonian, pulse.t_list
            duration = t_local[-1] - t_local[0]
            for op, coeff_local in term_curr:
                coeff_global = np.zeros(N, dtype = complex)
                t_loc = t_global - curr
                mask = (t_loc >= t_local[0]) & (t_loc <= t_local[-1])
                # 一次searchsort
                indices = np.clip(np.searchsorted(t_local, t_loc[mask]) - 1, 0, len(coeff_local) - 1)
                coeff_global[mask] = coeff_local[indices]
                # for j, t in enumerate(t_global):
                #     t_loc = t - curr
                #     if t_loc >= t_local[0] and t_loc <= t_local[-1]:
                #         index = np.clip(np.searchsorted(t_local, t_loc) - 1, 0, len(coeff_local) - 1)
                #         coeff_global[j] = coeff_local[index]
                hamiltonian.append([op, coeff_global])
            curr += duration
        return hamiltonian, t_global
    
    def plot(self):
        '''
        绘制复合脉冲的Rabi频率包络线
        '''
        import matplotlib.pyplot as plt
        t_list = self.t_list
        Omega_values = [self.get_Omega(t) for t in t_list]
        plt.figure(figsize=(8, 4))
        plt.plot(t_list, Omega_values)
        plt.xlabel('Time (ns)')
        plt.ylabel('Rabi Frequency (GHz)')
        plt.title('Composite Pulse Rabi Frequency Envelope')
        plt.grid()
        plt.show()
    
    def get_kernel(self, qubit):
        '''
        获取复合脉冲的控制核函数，表示该复合脉冲对测量结果的影响，未来可以直接用来做卷积和反卷积
        :param qubit: 作用的Qubit对象，用于计算控制核
        '''
        from sqc.reconstruction.kernel import KernelEstimator

        estimator = KernelEstimator()
        self.t_samples, self.kernel = estimator.estimate(self, qubit)
        return self.t_samples, self.kernel
    

#定义一些常用脉冲序列，返回含时哈密顿量

def create_pulse(qubit:TransmonQubit, frame, type, t_list, omega_d, phase, angle = None, **kwargs):
    '''
    创建Pulse对象，给定参考系，波形，驱动频率，旋转角度（可选），旋转轴和其他参数，自动计算Rabi频率包络线，默认使用RWA，未来研究BC频移可设置is_rwa=False
    :param type: 脉冲类型，与signal类一致
    :param t_list: 时间列表（ns），用于生成Rabi频率序列
    :param kwargs: 脉冲参数，可以包括幅度，频率，相位，中心位置，宽度，直流偏置等
    '''
    Omega_signal = Signal(type=type, t_list=t_list, **kwargs)
    Omega_pulse = Pulse(frame, omega_d, phase, Omega=Omega_signal, is_rwa=True, qubit=qubit)
    if qubit.frequency == omega_d:  # 共振情况
        current_angle = Omega_pulse.get_angle_simple()
    else:
        current_angle = Omega_pulse.get_angle_simple()
    # 调整幅度以实现目标旋转角度
    if angle is not None:
        Omega_signal.params['amplitude'] *= angle / current_angle
    # 重新生成脉冲对象
    kwargs['amplitude'] = Omega_signal.params['amplitude']
    signal = Signal(type=type, t_list=t_list, **kwargs)
    pulse = Pulse(frame, omega_d, phase, Omega=signal, is_rwa=True, qubit=qubit)
    H_t = pulse.hamiltonian
    return QobjEvo(H_t, tlist = t_list)



def create_ramsey_pulse(t_rabi, tau, omega_d = 0.0, phase1 = np.pi/2, phase2=0.0):
    '''
    创建Ramsey序列的复合脉冲对象，包含两个π/2脉冲和一个等待时间tau
    :param t_rabi: π/2脉冲的时间列表（ns）
    :param tau: 等待时间（ns）
    '''
    if tau != 0.0:
        Omega_0 = Signal(
            type = 0,
            t_list = np.linspace(0, tau, 100)  # ns
        )
    

    Omega_1 = Signal(
        type = 1,
        t_list = t_rabi,
        amplitude = ( np.pi / 2.0 ) / ( t_rabi[-1] - t_rabi[0] )  # GHz
    )
    pulses = []
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase1,
        Omega = Omega_1,
        is_rwa = True
    ))
    if tau != 0.0:
        pulses.append(Pulse(
            frame = 1,
            omega_d = omega_d,
            phase = 0.0,
            Omega = Omega_0,
            is_rwa = True
        ))
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase2,
        Omega = Omega_1,
        is_rwa = True
    ))
    composite_pulse = CompositePulse(pulses)
    return composite_pulse

def create_diff_echo_pulse(t_rabi, tau, t_int, t_rep, k, omega_d, phase1 = 0.0, phase2 = np.pi/2, phase3 = np.pi/2):
    '''
    创建差分回波序列：pi/2 - [tau - pi - tau' - (tau + t_int) - pi - tau'']^k - pi/2
    其中，pi脉冲长度与pi/2脉冲相同，phase1, phase2, phase3分别为第一个pi/2脉冲，默认朝x轴，pi脉冲，默认朝y轴，和第二个pi/2脉冲，，默认朝y轴，tau'和tau''由总周期t_rep和其他参数自动计算
    '''
    
    # 自由演化波形
    Omega_0 = Signal(
        type = 0,
        t_list = np.linspace(0, tau, 100)  # ns
    )
    Omega_01 = Signal(
        type = 0,
        t_list = np.linspace(0, t_rep + t_int - t_rabi[-1] + t_rabi[0], 100)  # ns
    )
    Omega_02 = Signal(
        type = 0,   
        t_list = np.linspace(0, t_rep - tau - t_int - (t_rabi[-1] - t_rabi[0]), 100)  # ns
    )
    # pi/2
    Omega_1 = Signal(
        type = 1,   
        t_list = t_rabi,
        amplitude = ( np.pi / 2.0 ) / ( t_rabi[-1] - t_rabi[0] )  # GHz
    )
    # pi
    Omega_2 = Signal(
        type = 1,
        t_list = t_rabi,
        amplitude = ( np.pi ) / ( t_rabi[-1] - t_rabi[0] )  # GHz
    )
    pulses = []
    # pi/2
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase1,
        Omega = Omega_1,
        is_rwa = True
    ))
    for _ in range(k):
        # tau
        pulses.append(Pulse(
            frame = 1,
            omega_d = omega_d,
            phase = 0.0,
            Omega = Omega_0,
            is_rwa = True
        ))
        # pi
        pulses.append(Pulse(
            frame = 1,
            omega_d = omega_d,
            phase = phase2,
            Omega = Omega_2,
            is_rwa = True
        ))
        # tau' + tau + t_int
        pulses.append(Pulse(
            frame = 1,
            omega_d = omega_d,
            phase = 0.0,
            Omega = Omega_01,
            is_rwa = True
        ))
        # pi
        pulses.append(Pulse(
            frame = 1,
            omega_d = omega_d,
            phase = phase2,
            Omega = Omega_2,
            is_rwa = True
        ))
        # tau''
        pulses.append(Pulse(
            frame = 1,
            omega_d = omega_d,
            phase = 0.0,
            Omega = Omega_02,
            is_rwa = True
        ))
    # pi/2
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase3,
        Omega = Omega_1,
        is_rwa = True
    ))
    composite_pulse = CompositePulse(pulses)
    return composite_pulse


def create_echo_pulse(t_rabi, tau, omega_d = 0.0, phase1 = 0.0, phase2 = 0.0, phase3 = 0.0):
    '''
    
    创建Spin Echo序列的复合脉冲对象，包含两个π/2脉冲和一个π脉冲，以及等待时间tau
    :param t_rabi: π/2脉冲的时间列表（ns）
    :param tau: 等待时间（ns）
    :param phase1: 第一个π/2脉冲的相位（rad），一般沿x轴
    :param phase2: π脉冲的相位（rad），一般沿y轴
    :param phase3: 分析脉冲的相位（rad），可以取x或y轴，或者直接扫描相位以得到Ramsey干涉图
    '''
    Omega_0 = Signal(
        type = 0,
        t_list = np.linspace(0, tau, 100)  # ns
    )
    Omega_1 = Signal(
        type = 1,
        t_list = t_rabi,
        amplitude = ( np.pi / 2.0 ) / ( t_rabi[-1] - t_rabi[0] )  # GHz
    )
    Omega_2 = Signal(
        type = 1,
        t_list = t_rabi,
        amplitude = ( np.pi ) / ( t_rabi[-1] - t_rabi[0] )  # GHz
    )
    pulses = []
    # pi/2
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase1,
        Omega = Omega_1,
        is_rwa = True
    ))
    # tau
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = 0.0,
        Omega = Omega_0,
        is_rwa = True
    ))
    # pi
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase2,
        Omega = Omega_2,
        is_rwa = True
    ))
    # tau
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = 0.0,
        Omega = Omega_0,
        is_rwa = True
    ))
    # pi/2
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase3,
        Omega = Omega_1,
        is_rwa = True
    ))
    composite_pulse = CompositePulse(pulses)
    return composite_pulse

def create_cpmg_pulse(t_rabi, tau, n, omega_d, phase1 = 0.0, phase2 = np.pi/2, phase3 = np.pi/2):
    '''
    创建CPMG序列的复合脉冲对象，包含两个π/2脉冲和n个π脉冲，以及等待时间tau
    :param t_rabi: π/2脉冲的时间列表（ns）
    :param tau: 等待时间（ns）
    :param n: π脉冲的数量
    :param phase1: 第一个π/2脉冲的相位（rad），一般沿x轴
    :param phase2: π脉冲的相位（rad），一般沿y轴
    :param phase3: 分析脉冲的相位（rad），可以取x或y轴，或者直接扫描相位以得到Ramsey干涉图
    '''
    # tau/2
    Omega_0 = Signal(
        type = 0,
        t_list = np.linspace(0, tau/2, 100)  # ns
    )
    # tau
    Omega_1 = Signal(
        type = 0,
        t_list = np.linspace(0, tau, 100)  # ns
    )
    # pi/2
    Omega_2 = Signal(
        type = 1,
        t_list = t_rabi,
        amplitude = ( np.pi / 2.0 ) / ( t_rabi[-1] - t_rabi[0] )  # GHz
    )
    # pi
    Omega_3 = Signal(
        type = 1,
        t_list = t_rabi,
        amplitude = ( np.pi ) / ( t_rabi[-1] - t_rabi[0] )  # GHz
    )
    pulses = []
    # pi/2
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase1,
        Omega = Omega_2,
        is_rwa = True
    ))
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = 0.0,
        Omega = Omega_0,
        is_rwa = True
    ))
    for _ in range(n):
        # pi
        pulses.append(Pulse(
            frame = 1,
            omega_d = omega_d,
            phase = phase2,
            Omega = Omega_3,
            is_rwa = True
        ))
        # tau
        pulses.append(Pulse(
            frame = 1,
            omega_d = omega_d,
            phase = 0.0,
            Omega = Omega_1,
            is_rwa = True
        ))
    # tau/2
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = 0.0,
        Omega = Omega_0,
        is_rwa = True   
    ))
    # pi/2
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase3,
        Omega = Omega_2,
        is_rwa = True
    ))
    composite_pulse = CompositePulse(pulses)
    return composite_pulse

def create_cryoscope_pulse(t_rabi, tau, omega_d, phase1 = np.pi/2, phase2 = 0.0):
    '''
    创建cryoscope测量协议的复合脉冲对象，包含一个长方形脉冲和一个短脉冲，长方形脉冲用于模拟系统的响应，短脉冲用于刺激系统并测量响应
    '''
    Omega_0 = Signal(
        type = 1,
        t_list = np.linspace(0, tau, 100),  # ns
        amplitude = 0.0  # GHz
    )
    Omega_1 = Signal(
        type = 1,
        t_list = t_rabi,
        amplitude = ( np.pi / 2.0 ) / ( t_rabi[-1] - t_rabi[0] )  # GHz
    )
    pulses = []

    # pi/2-Y
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase1,
        Omega = Omega_1,
        is_rwa = True
    ))
    # tau
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = 0.0,
        Omega = Omega_0,
        is_rwa = True
    ))
    # pi/2
    pulses.append(Pulse(
        frame = 1,
        omega_d = omega_d,
        phase = phase2,
        Omega = Omega_1,
        is_rwa = True
    ))
    composite_pulse = CompositePulse(pulses)

    return composite_pulse
